apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arduino-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:filip-krajcovic/arduino-greenhouse-api-config.git
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arduino
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true