apiVersion: apps/v1
kind: Deployment
metadata:
  name: arduino-api
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: arduino-api
  template:
    spec:
      containers:
      - env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: arduino-api--mongodb
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: arduino-api--mongodb
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: arduino-api--mqtt
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: arduino-api--mqtt
        envFrom:
        - configMapRef:
            name: arduino-api
        - configMapRef:
            name: arduino-api--mqtt
        - configMapRef:
            name: arduino-api--mongodb
        image: arduino-api
        imagePullPolicy: Always
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /health/live
        #     port: 5000
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        #   successThreshold: 1
        #   terminationGracePeriodSeconds: 60
        #   timeoutSeconds: 10
        name: arduino-api
        ports:
        - containerPort: 5000
          protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 5000
        #   initialDelaySeconds: 90
        #   periodSeconds: 60
        #   successThreshold: 1
        #   timeoutSeconds: 10
        resources:
          limits:
            cpu: 1
            memory: 256Mi
          requests:
            cpu: 0.5
            memory: 256Mi
