apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: backend
  app.kubernetes.io/created-by: krajcot
  app.kubernetes.io/managed-by: argo-cd
  app.kubernetes.io/name: arduino-api

#nameSuffix: -ms

images:
- name: arduino-api
  newName: filipkrajcovic/arduino-greenhouse-api
  newTag: 0.0.11
resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: arduino-api
  envs:
  - configurations/application.properties
  options:
    disableNameSuffixHash: true
- name: arduino-api--mongodb
  envs:
  - configurations/mongodb.properties
  options:
    disableNameSuffixHash: true

