apiVersion: v1
kind: Service
metadata:
  name: arduino-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app.kubernetes.io/name: arduino-api